FROM quay.io/ai-lab/nvidia-bootc:latest
 Setup /usr/lib/containers/storage as an additional store for images.
# Remove once the base images have this set by default.
RUN sed -i -e '/additionalimage.*/a "/usr/lib/containers/storage",' \
        /etc/containers/storage.conf

# Added for running as an OCI Container to prevent Overlay on Overlay issues.
VOLUME /var/lib/containers

RUN podman pull --arch=${TARGETARCH} --root /usr/lib/containers/storage ${INSTRUCTLAB_IMAGE}

RUN podman system reset --force 2>/dev/null
COPY ${WRAPPER} /usr/local/bin/ilab
